export enum ListaTopDezENUM {
    ITENS_MAIS_PERDIDOS = 'ITENS_MAIS_PERDIDOS',
    ITENS_MAIS_PERDIDOS_HOMEM = 'ITENS_MAIS_PERDIDOS_HOMEM',
    ITENS_MAIS_PERDIDOS_MULHERES = 'ITENS_MAIS_PERDIDOS_MULHERES',
    ITENS_MAIS_PERDIDOS_SEMANA = 'ITENS_MAIS_PERDIDOS_SEMANA',
    ITENS_MAIS_PERDIDOS_MES = 'ITENS_MAIS_PERDIDOS_MES',
}
